- name: Determine ALB facts
  elb_application_lb_info:
    profile: "{{ profile|default(omit) }}"
    region: "{{ region }}"
    names: "{{ load_balancer_name }}"
  register: elb_application_lb_facts

- name: Point DNS at ALBs
  include_role:
    name: aws_route53
  vars:
    aws_route53_profile: "{{  aws_route53_profile_public|default(profile|default()) }}"
    aws_route53:
      private_zone: no
      zone: "{{ tld_name_external }}"
      record: "{{ item }}"
      value: "{{ elb_application_lb_facts.load_balancers[0].dns_name }}"
      type: CNAME
  with_items: "{{ alb_route53_dnses|default([alb_route53_dns]) }}"
  when: target_groups is defined and target_groups.keys()|length > 0
